### ISSUE TITLE
"Callback is not a function"

### ISSUE THREAD

**Issue by qozle** [qozle/wall-of-cats#1]
Randomly getting:

```
/var/www/html/01014.org/public_html/srv/node_modules/needle/lib/needle.js:468
      return callback(err, resp, resp ? resp.body : undefined);
             ^

TypeError: callback is not a function
    at done (/var/www/html/01014.org/public_html/srv/node_modules/needle/lib/needle.js:468:14)
    at PassThrough.<anonymous> (/var/www/html/01014.org/public_html/srv/node_modules/needle/lib/needle.js:719:9)
    at PassThrough.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

It looks like somewhere, needle is expecting a callback function and not finding it.  There are only a few needle requests in the code so it shouldn't be too hard to track down.  Might be at line 113-124?:

```
// Function to connect the stream
function streamConnect() {
  const options = {
    timeout: 20000,
    compressed: true
  }

  const stream = needle.get(streamURL, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  }, options);
```

**Comment by qozle** [comment]
This error can be reproduced (I think) if the server is closed and then opened again quickly.  Which makes me think it has something to do with the twitter server.  Also sometimes this error is being returned kind of randomly.  Maybe it has to do with the timeout function / reconnect logic?:

```
  const filteredStream = streamConnect()
  let timeout = 0;
  filteredStream.on('timeout', () => {
    // Reconnect on error
    console.warn('A connection error occurred. Reconnecting…');
    console.log('hey, we timed out from the Twitter servers, bro');
    setTimeout(() => {
      timeout++;
      streamConnect(token);
    }, 2 ** timeout);
    streamConnect(token);
  })
  filteredStream.on('header', () => {
    console.log('Bro, we connected to the twitter servers, bro.')
  })
})();
```

**Comment by qozle** [comment]
fixed by 7054f1dfb51f3849dbcd7e3b49f7c5512b0c06d0

**Comment by Spanospy** [comment]
Hey there, I think I'm getting the same issue as you when using needle in my own code to streamConnect to twitter. I'm pretty much using the exact code from the [Twitter sample code](https://github.com/twitterdev/Twitter-API-v2-sample-code/blob/master/Filtered-Stream/filtered_stream.js). Could you pinpoint what you changed in order to fix it?

Exact error I'm getting is:

`TypeError: callback is not a function
    at done (C:\Users\Spanospy\Documents\discord bot\node_modules\needle\lib\needle.js:468:14)
    at ClientRequest.had_error (C:\Users\Spanospy\Documents\discord bot\node_modules\needle\lib\needle.js:478:5)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by qozle** [comment]
Hey.  I believe what this is is that, as the error says, somewhere needle is expecting a callback and there isn't one.  I would look at needle's [npm](https://www.npmjs.com/package/needle) and check what kind of call you're using with needle. 

I'll be honest it's been a little while since I worked on this code so I don't totally remember.  But as the error says, it has something to do with needle expecting a callback and there not being one.  I think I had some extra parameters in one of my needle calls, so needle would or wouldn't take a callback but because I had an extra parameter, it was using it as a callback but it obviously wasn't a callback.  

I'm looking at the sample code now too- it loooooks like their code should be ok.  So I guess check that you're not passing in any extra parameters as data or options or something where it shouldn't be.  Would be my advice.  Or maybe try changing the needle calls from direct calls:
```
needle('get', someURL, someOptions)
```
to method calls:
```
needle.get(someURL, someOptions)
```

Dunno if that would actually change anything but maybe it's worth a try.

It looks like in my push, I had just removed some callbacks that I had actually added in myself.  

Hope that makes sense?  Best of luck!  Lemme know if you solve it.

**Comment by Spanospy** [comment]
Haven't tried any changes to the code yet, but running it with `set DEBUG=needle` resulted in this just before the TypeError:

`  needle Request error Error: read ECONNRESET`
`    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {`
`  errno: 'ECONNRESET',`
`  code: 'ECONNRESET',`
`  syscall: 'read'`
`} +3h`

I'll get around to trying method calls and seeing if that works some other time. Bit tired with this issue.

**Comment by Spanospy** [comment]
Okay, so I was already using method calls for get. The code was trying to input a third parameter however, so I tried without that (and add in code that treats ECONNRESET as if it was a timeout).

No clue what is happening now though, as it now silently stops instead of giving me an error.

**Comment by qozle** [comment]
If it's not giving any errors, maybe try a putting it in a try / catch
block?  Or if there are promises, add a .catch to them?

The twitter API is a little jenk I think, as is their example code.  I had
a problem with another example code of theirs, for posting tweets (using
V1).  In their example code, they used an outdated request library (called
Request).  So I reformatted it using Needle and I know I had the code right
but it just wasn't working with Needle (had to do with the oAuth headers,
and I know mine were correct because I put the data in variables and used
the same variables with Request).  They said they had the same problem and
to feel free to do a pull request lol.  That was after they sent me a
totally generic response and didn't even read my post.

I wrestled with that "no callback" issue for a while.  Do you have your
code on github?  Maybe I could take a look at what you've got going on.

**Comment by Spanospy** [comment]
I've trimmed it down a lot [here](https://github.com/Spanospy/twitter-to-discord). The code uses discord to activate the stream which I know works.

Also, turned out that it silently stops streaming because of the econnreset, and it might be caused by whenever there's a new tweet but I'm not sure about that. I can get one tweet from twitter user botdaft before it has an issue later on, haven't tested it with other users.

Sorry about this by the way

**Comment by qozle** [comment]
hey it's no problem!  this is what github is about.  it's fun to squash
bugs and learn.  I'll take a peak at the code at some point soon.  Let me
know if you end up sorting it out.

**Comment by Spanospy** [comment]
I'm speculating that my issue might be this: https://github.com/nodejs/node/issues/27916

Not entirely sure how to get around this, might have to do something with uncaughtException.

**Comment by qozle** [comment]
This is interesting.  That's great research.  I took a peak at this a day or two ago but just haven't had time to respond- I'm just starting a new full time coding job (my first!) and I'm doing school full time as well.  So I'm a bit swamped.

I might have an response.abort() in my code somewhere.  I remember writing that somewhere.  And one of the comments says that aborting the request might help.  

Sorry I can't be more of help right now.  This project using twitter for me is done- it more or less works and was really just a portfolio project which served it's purpose (I got hired).  I may or may not revisit it in the future.  It's good to look into this stuff, but if it keeps hanging you up, maybe you can put it in a try / catch block and ignore it?  One way or another I stopped it from being an issue in my code, even if that just means passing over the thrown error.

**Comment by Spanospy** [comment]
Not a problem! Thanks for taking the time to answer. Eventually I'll get this sorted out. (I'll edit this message when I do, so this doesn't become another "Nevermind, I solved it!" thread.)

Thanks again!

**Comment by Spanospy** [comment]
Actually, my theory on why it breaks sometimes is maybe when I check the twitter page of the account (or it's tweets). Was working all fine until I checked the twitter account.
